# Generated by Django 6.1.1 on 2026-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
