# Generated by Django 6.1.1 on 2026-09-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_add_recurring_template_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
