# Generated by Django 6.1.1 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0003_household_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="period_key",
            field=models.CharField(
                blank=True,
                help_text="Recurrence period key for spawned chores; null for one-offs.",
                max_length=32,
                null=True,
            ),
        ),
    ]
